apiVersion: v2
name: loft
description: Secure Cluster Sharing + Self-Service Namespace Provisioning
home: https://loft.sh
icon: https://static.devspace.cloud/loft/logo/loft-logo.svg
sources:
- https://github.com/devspace-cloud/loft
keywords:
- developer
- development
- sharing
- share
- multi-tenancy
- tenancy
- cluster
- space
- namespace
maintainers:
- name: DevSpace Technologies Inc.
  email: info@devspace.cloud
  url: https://twitter.com/DevSpace

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

version: v1.9.3
