apiVersion: v1
kind: Service
metadata:
  name: loft-ingress-wakeup-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loft.fullname" . }}
    loft.sh/service: {{ template "loft.fullname" . }}-ingress-wakeup-agent
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - name: http-wakeup
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: {{ template "loft.fullname" . }}
    release: {{ .Release.Name }}
