apiVersion: v1
kind: Service
metadata:
  name: loft-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loft.fullname" . }}
    loft.sh/service: {{ template "loft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: {{ .Values.service.httpNodePort }}
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      nodePort: {{ .Values.service.httpsNodePort }}
      protocol: TCP
    - name: wakeup
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: {{ template "loft.fullname" . }}
    release: {{ .Release.Name }}
